In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
df = pd.read_csv('/home/atg/Aadi/Christ College/Principles of Data Analytics/EDA assignment/EDA/House_Price_India.csv')

In [3]:
df.head()

,id,No of bedrooms,living area,Postal Code,Lattitude,Longitude,No of schools nearby,Distance from the airport,Price
0,6762810635,4,2920,122004,52.8878,-114.470,2,51,1400000
1,6762810998,5,2910,122004,52.8852,-114.468,1,53,1200000
2,6762812605,4,3310,122005,52.9532,-114.321,3,76,838000
3,6762812919,3,2710,122006,52.9047,-114.485,1,51,805000
4,6762813105,3,2600,122007,52.9133,-114.590,1,67,790000

In [4]:
df.shape

(14619, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14619 entries, 0 to 14618
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         14619 non-null  int64
 1   No of bedrooms             14619 non-null  int64
 2   living area                14619 non-null  int64
 3   Postal Code                14619 non-null  int64
 4   Lattitude                  14619 non-null  float64
 5   Longitude                  14619 non-null  float64
 6   No of schools nearby       14619 non-null  int64
 7   Distance from the airport  14619 non-null  int64
 8   Price                      14619 non-null  int64
dtypes: float64(2), int64(7)
memory usage: 1.0 MB

In [6]:
df.describe()

,id,No of bedrooms,living area,Postal Code,Lattitude,Longitude,No of schools nearby,Distance from the airport,Price
count,1.461900e+04,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,14619.000000,1.461900e+04
mean,6.762821e+09,3.379233,2098.156851,122033.064300,52.792843,-114.403996,2.012244,64.951433,5.388063e+05
std,6.237162e+03,0.938655,928.218740,19.081451,0.137525,0.141325,0.817312,8.936129,3.672294e+05
min,6.762810e+09,1.000000,370.000000,122003.000000,52.385900,-114.709000,1.000000,50.000000,7.800000e+04
25%,6.762815e+09,3.000000,1440.000000,122017.000000,52.707600,-114.519000,1.000000,57.000000,3.200000e+05
50%,6.762821e+09,3.000000,1930.000000,122032.000000,52.806400,-114.421000,2.000000,65.000000,4.500000e+05
75%,6.762826e+09,4.000000,2570.000000,122048.000000,52.908900,-114.315000,3.000000,73.000000,6.450000e+05
max,6.762832e+09,33.000000,13540.000000,122072.000000,53.007600,-113.505000,3.000000,80.000000,7.700000e+06

In [7]:
fig = px.scatter_mapbox(
    df,  # Our DataFrame
    lat='Lattitude',
    lon='Longitude',
    #center={"lat": 19.43, "lon": -99.13},  # Map will be centered on Mexico City
    width=600,  # Width of map
    height=600,  # Height of map
    hover_data=["Price"],  # Display price when hovering mouse over house
)